### ISSUE TITLE
IaR login

### ISSUE THREAD

**Issue by burnhaj** [CtrlAltJesse/IAmRespondingKiosk#1]
Jesse,

I have set up 6-8 of the pi kiosks and they work wonderfully.  Very easy to do.  Thank you.
I have found that the app url works better if you use:
https://www.iamresponding.com/v3/Pages/memberlogin.aspx

This may be related to the revisions to the IaR website in recent months.

Jim

**Comment by CtrlAltJesse** [comment]
Hi Jim,

First off, I am super happy you find this useful! :-) 

I'm swinging by my firehouse tonight, I'll make this change and test (just to make sure this doesn't break things), and change the guide.

I have tried searching, but no insight into their long term strategy regarding the web dashboard so unfortunately I am unable to get ahead of any changes they have coming down the pipe.

**Comment by jbobweis** [comment]
Thank you for this.  I am trying to get this to work in my firehouse, but am VERY new to the Pi world and programming.  I was able to follow your directions up to Section 3.  I get to the point where I have to add the new file called .xsession.  I am dumb, and don't know how to do that.  At this point, I am stuck there.  Any help would be greatly appreciated so I can get this going at my department (Port Washington, Wisconsin).

**Comment by burnhaj** [comment]
use nano, the command line text editor in linux, same as in the previous step: sudo nano /home/pi/.xsession this will create an an empty text file named .xsession..copy and paste in the two lines (or just type them in); cntrl-x, y, enter to save.

---------- Original Message ----------

**Comment by bradjtrammell** [comment]
First off. I wanted to say this an amazing concept. As an Administrator that manages multiple active firehouses with multiple displays, I've been searching for something like this for almost 2 years. I'm glad to see someone has put one together!

I do have some questions though. I followed your guide to a tee however when the Pi boots, I am just sitting at a black screen. There is no cursor and I have no SSH access to the Pi at that point. I have no ability to do anything with the Pi at that point. Additionally, when I test the IaRInjector after entering my credentials, I get the standard "He's Dead Jim" chrome page for when a plugin or URL redirect has failed. I'm not sure if that is causing the issue.

Additionally, I wanted to mention that at our fire house, one of our members works for IamResponding and I think they'd really be interested in what you've made here. I can put you in contact with him if you're interested in working directly with IAR on further development.

**Comment by CtrlAltJesse** [comment]
I am going to close this issue as I have tested and made the change to the tutorial - however it should probably be noted that it seems like the IAR Injection tool is smart enough to navigate to the login page from multiple URLs in the iamresponding.com domain, including dashboard.iamresponding.com and iamresponding.com
