### ISSUE TITLE
Black Screen at Boot

### ISSUE THREAD

**Issue by bradjtrammell** [CtrlAltJesse/IAmRespondingKiosk#2]
First off. I wanted to say this an amazing concept. As an Administrator that manages multiple active firehouses with multiple displays, I've been searching for something like this for almost 2 years. I'm glad to see someone has put one together!

I do have some questions though. I followed your guide to a tee however when the Pi boots, I am just sitting at a black screen. There is no cursor and I have no SSH access to the Pi at that point. I have no ability to do anything with the Pi at that point. Additionally, when I test the IaRInjector after entering my credentials, I get the standard "He's Dead Jim" chrome page for when a plugin or URL redirect has failed. I'm not sure if that is causing the issue.

Additionally, I wanted to mention that at one of our fire houses, one of our members works for IamResponding (as it's based here) and I think they'd really be interested in what you've made here. I can put you in contact with him if you're interested in working directly with IAR on further development.

**Comment by bradjtrammell** [comment]
Tried a second time to install, and it installed flawlessly. Disregard my post. 

Offer to put you in contact with IamResponding directly is still valid.

**Comment by CtrlAltJesse** [comment]
Hi @bradjtrammell, apologies on the delay but I would absolutely be interested in that.
Having a heads up of changes down the pipe would be good as well, so this guide can be updated before rolling out *cough* cookie dialog *cough* :-)
