### ISSUE TITLE
Cookies Banner Prevents Login

### ISSUE THREAD

**Issue by Kingsford07** [CtrlAltJesse/IAmRespondingKiosk#3]
The new yellow banner regarding Cookies on IAR's website is preventing devices from logging in. The page just seems to refresh over and over again.

**Comment by CtrlAltJesse** [comment]
Yup, aware of this when it happened to _every single screen in our FD_, working on a fix now :-)

**Comment by CtrlAltJesse** [comment]
First off, my last comment came off a bit snarky - please know that all snark is pointed in the direction of whomever rolled out this change @ I Am Responding :-p
After tinkering with a Tampermonkey script, I believe I have a fix I will be documenting tomorrow as well as ammending the new-build instructions.

**Comment by CtrlAltJesse** [comment]
Tutorial on a fix is located [Here!](https://github.com/CtrlAltJesse/IAmRespondingKiosk/blob/master/cookieacceptfix.md)

Please let me know how this works out.
