### ISSUE TITLE
Dashboard URL update.

### ISSUE THREAD

**Issue by stonewalljones** [CtrlAltJesse/IAmRespondingKiosk#4]
I believe that this URL needs to be updated to the new dashboard https://dashboard.iamresponding.com

https://github.com/CtrlAltJesse/IAmRespondingKiosk/blob/aeed2f574ace53acb1dac6a532217f0855860ef4/.xsession#L5

**Comment by CtrlAltJesse** [comment]
Good catch, meant to do this a while ago!

Readme and .xsession are both updated with the new URL
