### ISSUE TITLE
stuck in kiosk mode

### ISSUE THREAD

**Issue by wtalada** [CtrlAltJesse/IAmRespondingKiosk#5]
ran your solution on a pi zero w. now cannot get back into windowed mode to add extensions to chrome or modify the iar injector. time is coming out of sync on the screen and would like to add an automated refresh extension to help it keep on time. alt+f4 only produces a blank screen and ctrl alt f2 and startx only opens the kiosk again.

**Comment by CtrlAltJesse** [comment]
Hi, apologies for the delay.

If you are able to get back to the terminal, you should be able to modify your xsession file (/home/pi/.xession) and remove `--kiosk` in the last line:
`chromium-browser https://dashboard.iamresponding.com & exec matchbox-window-manager`

Once you reboot, this should stop Chrome from starting in kiosk mode and you should be able to modify as needed.
