### ISSUE TITLE
Repeated login attempts

### ISSUE THREAD

**Issue by jaburnham** [CtrlAltJesse/IAmRespondingKiosk#6]
Something isn't working correctly.  When I get to the end of section 3 Chromium Setup and navigate to dashboard.iamresponding.com, I get logged in correctly but it continually cycles through the login screen every couple seconds.  I have tried Raspbian Buster as well as Bullseye with the same results for each.  I have used these scripts in the past successfully.  The current instructions/userscript/etc. result in the repeated logins.

I will go make a copy of the sd card for the pi that has worked properly for years and try that.

**Comment by jaburnham** [comment]
I solved my issue by downloading the IAR image for the pi which now includes an autoloading kiosk mode.  Disabled TTD by commenting out the TTDcheck line in /etc/xdg/lxsession/LXDE-pi/autostart.

**Comment by CtrlAltJesse** [comment]
Thanks for including the resolution notes above!

**Comment by LoosveltN** [comment]
There's an IAR image for the Raspberry PI?

**Comment by jaburnham** [comment]
Try this link:

https://download.iamresponding.com/autolauncher/ttd-autolauncher-raspberry.zip

You may need to be logged in.

**Comment by jaburnham** [comment]
Or here are all the instructions:

https://www.iamresponding.com/v3/articles/TTDInstructions.pdf
